[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
durations = 0
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
