name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test_py37:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install SRRS
        run: pip install .

      - name: Install testing dependencies
        run: pip install -r requirements_test.txt 

      - name: Run tests with cov
        run: pytest --cov=src --durations=0 tests

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2

