name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install SRRS
        run: pip install -e .

      - name: Install testing dependencies
        run: pip install -r requirements_test.txt 

      - name: Run tests
        run: pytest tests

